
name:              "高峪泷"
description:        ""

url:                ""
author:             "CrazyRt"
email:              "wrtmg@oulook.com"
gravatar_hash:      ""
twitter:            "CrazyRt"
email:              "wrtmg@outlook.com"
github:             "crazyrt"
steam:              "docktimy"
linkedin:           "高峪泷"
facebook:           "高峪泷"

disqus_shortname:   "CrazyRt"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
